---
spec_version: '1.0'
indicators:
  probe_duration_ms: avg_over_time(probe_duration_seconds{instance="helloservice.litmus-chaos.svc:80",job="blackbox-kubernetes-services"}[$DURATION_SECONDS:1s])*1000
  probe_success_percentage: avg_over_time(probe_success{instance="helloservice.litmus-chaos.svc:80",job="blackbox-kubernetes-services"}[$DURATION_SECONDS:1s])*100




